# ILAS Configuration Example - PX4 Controller
# This is an example configuration for ILAS with PX4 flight controller

detection:
  detection_range: 20.0  # meters
  min_confidence: 0.6
  sensors:
    - type: lidar
      enabled: true
      fov: 360  # degrees
      max_range: 30.0
    - type: camera
      enabled: true
      fov: 90
      resolution: [640, 480]
    - type: ultrasonic
      enabled: true
      max_range: 5.0
    - type: ml_camera
      enabled: true
      model_path: "models/yolov5s.pt" # Local path to the model
      confidence_threshold: 0.4
      device: "cpu" # or "cuda:0"
      focal_length: 500.0 # Approximate focal length in pixels
      classes_to_detect:
        - person
        - car
        - bicycle
        - bus
        - truck

avoidance:
  strategy: potential_field  # Options: potential_field, vector_field, dynamic_window, rrt
  safety_margin: 2.0  # meters
  max_avoidance_distance: 10.0
  avoidance_gain: 1.0
  max_velocity: 5.0  # m/s
  max_acceleration: 2.0  # m/s^2
  prediction_time: 1.0  # seconds

landing:
  landing_mode: terrain  # Options: precision, terrain, emergency, vertical, slope
  min_landing_size: [2.0, 2.0]  # meters [width, depth]
  max_slope: 15.0  # degrees
  max_roughness: 0.3  # 0.0 to 1.0
  descent_rate: 0.5  # m/s
  hover_height: 2.0  # meters

controller:
  controller_type: px4  # Options: px4, ardupilot, dji, simulation
  connection_string: /dev/ttyUSB0
  baud_rate: 57600
  timeout: 5.0  # seconds

update_rate: 10.0  # Hz

geofence:
  enabled: true
  min_altitude: 5.0
  max_altitude: 100.0
  # Polygon points defining the horizontal boundary [[x1, y1], [x2, y2], ...]
  polygon_points:
    - [0, 0]
    - [100, 0]
    - [100, 100]
    - [0, 100]

slam:
  map_size_pixels: 500
  map_size_meters: 10
  scan_size: 360
  scan_rate_hz: 10
  detection_angle_degrees: 360
  distance_no_detection_mm: 12000
