# ILAS Configuration Example - Simulation

detection:
  detection_range: 20.0
  min_confidence: 0.5
  sensors:
    - type: lidar
      enabled: true
    - type: camera
      enabled: true

avoidance:
  strategy: potential_field
  safety_margin: 2.0
  max_avoidance_distance: 10.0
  avoidance_gain: 1.0
  max_velocity: 5.0
  max_acceleration: 2.0
  prediction_time: 1.0

landing:
  landing_mode: terrain
  min_landing_size: [2.0, 2.0]
  max_slope: 15.0
  max_roughness: 0.3
  descent_rate: 0.5
  hover_height: 2.0

controller:
  controller_type: simulation
  connection_string: localhost
  baud_rate: 57600

update_rate: 10.0

failsafe:
  return_to_base_altitude: 30.0
  hold_position_duration: 60.0
  emergency_descent_rate: 1.0

timeouts:
  controller: 5.0
  sensor: 5.0
